---
abstract: 'add throttling support to Mojo::UserAgent'
author:
  - 'Alex Efros <powerman@cpan.org>'
build_requires:
  Pod::Coverage: '0.18'
  Test::CheckManifest: '0.9'
  Test::More: '0'
  Test::Perl::Critic: '0'
  Test::Pod: '1.22'
  Test::Pod::Coverage: '1.08'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MojoX-UserAgent-Throttler
provides:
  MojoX::UserAgent::Throttler:
    file: lib/MojoX/UserAgent/Throttler.pm
    version: v0.1.0
requires:
  Mojolicious: '5.41'
  Sub::Throttler: v0.2.0
  Sub::Util: '1.40'
  perl: '5.010001'
  version: '0.77'
resources:
  license: http://www.opensource.org/licenses/mit-license.php
version: v0.1.0
